# Generated by Django 2.1.5 on 2019-04-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('TRUCK EN ROUTE TO WAREHOUSE', 'TRUCK EN ROUTE TO WAREHOUSE'), ('TRUCK WAITING FOR PACKAGE', 'TRUCK WAITING FOR PACKAGE'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('DELIVERED', 'DELIVERED')], default='CREATED', help_text='Package Status', max_length=50),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_status',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('EN ROUTE TO A WAREHOUSE', 'EN ROUTE TO A WAREHOUSE'), ('ARRIVED WAREHOUSE', 'ARRIVED WAREHOUSE'), ('DELIVERING', 'DELIVERING'), ('WAITING FOR PICKUP', 'WAITING FOR PICKUP'), ('INVAILD', 'INVAILD')], default='IDLE', help_text='Truck Status', max_length=50, null=True),
        ),
    ]
