# Generated by Django 2.1.5 on 2019-04-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dep_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='dep_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='des_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='des_y',
            field=models.IntegerField(null=True),
        ),
    ]
