# Generated by Django 2.1.5 on 2019-04-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_auto_20190423_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='descp',
            field=models.TextField(null=True),
        ),
    ]
