# Generated by Django 2.1.5 on 2019-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_auto_20190424_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='dep_x',
            field=models.IntegerField(help_text='Depature x'),
        ),
        migrations.AlterField(
            model_name='package',
            name='dep_y',
            field=models.IntegerField(help_text='Depature y'),
        ),
        migrations.AlterField(
            model_name='package',
            name='des_x',
            field=models.IntegerField(help_text='Destination x'),
        ),
        migrations.AlterField(
            model_name='package',
            name='des_y',
            field=models.IntegerField(help_text='Destination y'),
        ),
    ]
