# Generated by Django 2.1.5 on 2019-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0003_auto_20190424_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='speed',
            field=models.IntegerField(null=True),
        ),
    ]
