CREATE TABLE WORLD(
WORLD_ID INT PRIMARY KEY NOT NULL,
STATUS VARCHAR(10) NOT NULL
);

CREATE TABLE INSEQNUM(
ID BIGINT PRIMARY KEY NOT NULL,
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
PRIMARY KEY(ID, WORLD_ID)
);

CREATE TABLE OUTSEQNUM(
ID BIGSERIAL NOT NULL,
TYPE INT,
TRUCK_ID INT,
WH_ID INT,
PACKAGE_ID INT,
PACKAGE_X INT,
PACKAGE_Y INT,
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
TIME INT NOT NULL,
PRIMARY KEY(ID, WORLD_ID)
);

CREATE TABLE AINSEQNUM(
ID BIGINT PRIMARY KEY NOT NULL
);

CREATE TABLE AOUTSEQNUM(
ID BIGSERIAL PRIMARY KEY NOT NULL,
MSG VARCHAR(65535),
TIME INT NOT NULL
);


CREATE TABLE TRUCK(
TRUCK_ID INT NOT NULL,
X INT NOT NULL,
Y INT NOT NULL,
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
TRUCK_STATUS VARCHAR(50) NOT NULL DEFAULT 'IDLE',
PRIMARY KEY(TRUCK_ID, WORLD_ID)
);


CREATE TABLE PACKAGE(
PACKAGE_ID BIGINT NOT NULL,
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
TRUCK_ID INT REFERENCES TRUCK(TRUCK_ID),
USER_ID INT NULL REFERENCES UPS_PROFILE("user_id"),
PACKAGE_STATUS VARCHAR(20) NOT NULL DEFAULT 'CREATED',
DEP_X INT,
DEP_Y INT,
DES_X INT NOT NULL,
DES_Y INT NOT NULL,
DESCP TEXT,
COUNT INT,
PRIMARY KEY(PACKAGE_ID, WORLD_ID)
);

 
CREATE TABLE USERPACKAGE(
USER_ID INT NOT NULL REFERENCES UPS_PROFILE("user_id"),
PACKAGE_ID BIGINT NOT NULL
);

CREATE TABLE PRODUCT(
PRODUCT_ID BIGINT NOT NULL,
PACKAGE_ID BIGINT NOT NULL REFERENCES PACKAGE(PACKAGE_ID),
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
DESCRIPTION VARCHAR(100) NOT NULL,
COUNT INT NOT NULL,
PRIMARY KEY(PACKAGE_ID, WORLD_ID, PRODUCT_ID)
);

CREATE TABLE SHIPMENT(
SHIP_ID BIGINT NOT NULL,
PACKAGE_ID BIGINT NOT NULL REFERENCES PACKAGE(PACKAGE_ID),
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
PRIMARY KEY(SHIP_ID, WORLD_ID)
);

