CREATE TABLE WORLD(
WORLD_ID SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE PACKAGE(
PACKAGE_ID INT PRIMARY KEY NOT NULL,
USER_ID INT NOT NULL REFERENCES UPS_PROFILE("user_id"),
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
WH_ID INT NOT NULL,
SEQNUM INT NOT NULL,
TRUCK_ID INT NOT NULL,
TRUCK_STATUS VARCHAR(20) NOT NULL DEFAULT 'TRAVELING',
X INT NOT NULL,
Y INT NOT NULL
);


CREATE TABLE TRUCK(
PACKAGE_ID INT NOT NULL REFERENCES PACKAGE(PACKAGE_ID),
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
TRUCK_ID INT NOT NULL,
PRIMARY KEY(PACKAGE_ID, WORLD_ID)
);


CREATE TABLE SHIPMENT(
SHIP_ID SERIAL PRIMARY KEY NOT NULL,
PACKAGE_ID INT NOT NULL REFERENCES PACKAGE(PACKAGE_ID),
WORLD_ID INT NOT NULL REFERENCES WORLD(WORLD_ID),
STATUS VARCHAR(50) NOT NULL DEFAULT 'CREATED'
);

