// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ups_amazon.proto

#ifndef PROTOBUF_INCLUDED_ups_5famazon_2eproto
#define PROTOBUF_INCLUDED_ups_5famazon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ups_5famazon_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ups_5famazon_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[12]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ups_5famazon_2eproto();
namespace UA {
class ACommands;
class ACommandsDefaultTypeInternal;
extern ACommandsDefaultTypeInternal _ACommands_default_instance_;
class DetermineDst;
class DetermineDstDefaultTypeInternal;
extern DetermineDstDefaultTypeInternal _DetermineDst_default_instance_;
class DetermineTruck;
class DetermineTruckDefaultTypeInternal;
extern DetermineTruckDefaultTypeInternal _DetermineTruck_default_instance_;
class DetermineWarehouse;
class DetermineWarehouseDefaultTypeInternal;
extern DetermineWarehouseDefaultTypeInternal _DetermineWarehouse_default_instance_;
class InitWorld;
class InitWorldDefaultTypeInternal;
extern InitWorldDefaultTypeInternal _InitWorld_default_instance_;
class PackageInfo;
class PackageInfoDefaultTypeInternal;
extern PackageInfoDefaultTypeInternal _PackageInfo_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class SettleShipment;
class SettleShipmentDefaultTypeInternal;
extern SettleShipmentDefaultTypeInternal _SettleShipment_default_instance_;
class TruckDst;
class TruckDstDefaultTypeInternal;
extern TruckDstDefaultTypeInternal _TruckDst_default_instance_;
class TruckLocation;
class TruckLocationDefaultTypeInternal;
extern TruckLocationDefaultTypeInternal _TruckLocation_default_instance_;
class UCommands;
class UCommandsDefaultTypeInternal;
extern UCommandsDefaultTypeInternal _UCommands_default_instance_;
class WarehouseInfo;
class WarehouseInfoDefaultTypeInternal;
extern WarehouseInfoDefaultTypeInternal _WarehouseInfo_default_instance_;
}  // namespace UA
namespace google {
namespace protobuf {
template<> ::UA::ACommands* Arena::CreateMaybeMessage<::UA::ACommands>(Arena*);
template<> ::UA::DetermineDst* Arena::CreateMaybeMessage<::UA::DetermineDst>(Arena*);
template<> ::UA::DetermineTruck* Arena::CreateMaybeMessage<::UA::DetermineTruck>(Arena*);
template<> ::UA::DetermineWarehouse* Arena::CreateMaybeMessage<::UA::DetermineWarehouse>(Arena*);
template<> ::UA::InitWorld* Arena::CreateMaybeMessage<::UA::InitWorld>(Arena*);
template<> ::UA::PackageInfo* Arena::CreateMaybeMessage<::UA::PackageInfo>(Arena*);
template<> ::UA::Response* Arena::CreateMaybeMessage<::UA::Response>(Arena*);
template<> ::UA::SettleShipment* Arena::CreateMaybeMessage<::UA::SettleShipment>(Arena*);
template<> ::UA::TruckDst* Arena::CreateMaybeMessage<::UA::TruckDst>(Arena*);
template<> ::UA::TruckLocation* Arena::CreateMaybeMessage<::UA::TruckLocation>(Arena*);
template<> ::UA::UCommands* Arena::CreateMaybeMessage<::UA::UCommands>(Arena*);
template<> ::UA::WarehouseInfo* Arena::CreateMaybeMessage<::UA::WarehouseInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace UA {

// ===================================================================

class InitWorld :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.InitWorld) */ {
 public:
  InitWorld();
  virtual ~InitWorld();

  InitWorld(const InitWorld& from);

  inline InitWorld& operator=(const InitWorld& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InitWorld(InitWorld&& from) noexcept
    : InitWorld() {
    *this = ::std::move(from);
  }

  inline InitWorld& operator=(InitWorld&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const InitWorld& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InitWorld* internal_default_instance() {
    return reinterpret_cast<const InitWorld*>(
               &_InitWorld_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InitWorld* other);
  friend void swap(InitWorld& a, InitWorld& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InitWorld* New() const final {
    return CreateMaybeMessage<InitWorld>(nullptr);
  }

  InitWorld* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InitWorld>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InitWorld& from);
  void MergeFrom(const InitWorld& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InitWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 worldid = 1;
  bool has_worldid() const;
  void clear_worldid();
  static const int kWorldidFieldNumber = 1;
  ::google::protobuf::int64 worldid() const;
  void set_worldid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.InitWorld)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 worldid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class WarehouseInfo :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.WarehouseInfo) */ {
 public:
  WarehouseInfo();
  virtual ~WarehouseInfo();

  WarehouseInfo(const WarehouseInfo& from);

  inline WarehouseInfo& operator=(const WarehouseInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  WarehouseInfo(WarehouseInfo&& from) noexcept
    : WarehouseInfo() {
    *this = ::std::move(from);
  }

  inline WarehouseInfo& operator=(WarehouseInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const WarehouseInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WarehouseInfo* internal_default_instance() {
    return reinterpret_cast<const WarehouseInfo*>(
               &_WarehouseInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(WarehouseInfo* other);
  friend void swap(WarehouseInfo& a, WarehouseInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WarehouseInfo* New() const final {
    return CreateMaybeMessage<WarehouseInfo>(nullptr);
  }

  WarehouseInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<WarehouseInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const WarehouseInfo& from);
  void MergeFrom(const WarehouseInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WarehouseInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 whid = 1;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 1;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // required int32 wh_x = 2;
  bool has_wh_x() const;
  void clear_wh_x();
  static const int kWhXFieldNumber = 2;
  ::google::protobuf::int32 wh_x() const;
  void set_wh_x(::google::protobuf::int32 value);

  // required int32 wh_y = 3;
  bool has_wh_y() const;
  void clear_wh_y();
  static const int kWhYFieldNumber = 3;
  ::google::protobuf::int32 wh_y() const;
  void set_wh_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.WarehouseInfo)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 whid_;
  ::google::protobuf::int32 wh_x_;
  ::google::protobuf::int32 wh_y_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class DetermineWarehouse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.DetermineWarehouse) */ {
 public:
  DetermineWarehouse();
  virtual ~DetermineWarehouse();

  DetermineWarehouse(const DetermineWarehouse& from);

  inline DetermineWarehouse& operator=(const DetermineWarehouse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetermineWarehouse(DetermineWarehouse&& from) noexcept
    : DetermineWarehouse() {
    *this = ::std::move(from);
  }

  inline DetermineWarehouse& operator=(DetermineWarehouse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DetermineWarehouse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetermineWarehouse* internal_default_instance() {
    return reinterpret_cast<const DetermineWarehouse*>(
               &_DetermineWarehouse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DetermineWarehouse* other);
  friend void swap(DetermineWarehouse& a, DetermineWarehouse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetermineWarehouse* New() const final {
    return CreateMaybeMessage<DetermineWarehouse>(nullptr);
  }

  DetermineWarehouse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetermineWarehouse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetermineWarehouse& from);
  void MergeFrom(const DetermineWarehouse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetermineWarehouse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.WarehouseInfo warehouses = 1;
  int warehouses_size() const;
  void clear_warehouses();
  static const int kWarehousesFieldNumber = 1;
  ::UA::WarehouseInfo* mutable_warehouses(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::WarehouseInfo >*
      mutable_warehouses();
  const ::UA::WarehouseInfo& warehouses(int index) const;
  ::UA::WarehouseInfo* add_warehouses();
  const ::google::protobuf::RepeatedPtrField< ::UA::WarehouseInfo >&
      warehouses() const;

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.DetermineWarehouse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::WarehouseInfo > warehouses_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class DetermineTruck :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.DetermineTruck) */ {
 public:
  DetermineTruck();
  virtual ~DetermineTruck();

  DetermineTruck(const DetermineTruck& from);

  inline DetermineTruck& operator=(const DetermineTruck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetermineTruck(DetermineTruck&& from) noexcept
    : DetermineTruck() {
    *this = ::std::move(from);
  }

  inline DetermineTruck& operator=(DetermineTruck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DetermineTruck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetermineTruck* internal_default_instance() {
    return reinterpret_cast<const DetermineTruck*>(
               &_DetermineTruck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DetermineTruck* other);
  friend void swap(DetermineTruck& a, DetermineTruck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetermineTruck* New() const final {
    return CreateMaybeMessage<DetermineTruck>(nullptr);
  }

  DetermineTruck* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetermineTruck>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetermineTruck& from);
  void MergeFrom(const DetermineTruck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetermineTruck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.TruckLocation arrivedtrucks = 1;
  int arrivedtrucks_size() const;
  void clear_arrivedtrucks();
  static const int kArrivedtrucksFieldNumber = 1;
  ::UA::TruckLocation* mutable_arrivedtrucks(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >*
      mutable_arrivedtrucks();
  const ::UA::TruckLocation& arrivedtrucks(int index) const;
  ::UA::TruckLocation* add_arrivedtrucks();
  const ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >&
      arrivedtrucks() const;

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.DetermineTruck)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation > arrivedtrucks_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class TruckLocation :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.TruckLocation) */ {
 public:
  TruckLocation();
  virtual ~TruckLocation();

  TruckLocation(const TruckLocation& from);

  inline TruckLocation& operator=(const TruckLocation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TruckLocation(TruckLocation&& from) noexcept
    : TruckLocation() {
    *this = ::std::move(from);
  }

  inline TruckLocation& operator=(TruckLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TruckLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TruckLocation* internal_default_instance() {
    return reinterpret_cast<const TruckLocation*>(
               &_TruckLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(TruckLocation* other);
  friend void swap(TruckLocation& a, TruckLocation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TruckLocation* New() const final {
    return CreateMaybeMessage<TruckLocation>(nullptr);
  }

  TruckLocation* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TruckLocation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TruckLocation& from);
  void MergeFrom(const TruckLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TruckLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 whid = 2;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 2;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.TruckLocation)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 whid_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class DetermineDst :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.DetermineDst) */ {
 public:
  DetermineDst();
  virtual ~DetermineDst();

  DetermineDst(const DetermineDst& from);

  inline DetermineDst& operator=(const DetermineDst& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetermineDst(DetermineDst&& from) noexcept
    : DetermineDst() {
    *this = ::std::move(from);
  }

  inline DetermineDst& operator=(DetermineDst&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DetermineDst& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetermineDst* internal_default_instance() {
    return reinterpret_cast<const DetermineDst*>(
               &_DetermineDst_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(DetermineDst* other);
  friend void swap(DetermineDst& a, DetermineDst& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetermineDst* New() const final {
    return CreateMaybeMessage<DetermineDst>(nullptr);
  }

  DetermineDst* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetermineDst>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetermineDst& from);
  void MergeFrom(const DetermineDst& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetermineDst* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.TruckDst leavingtrucks = 1;
  int leavingtrucks_size() const;
  void clear_leavingtrucks();
  static const int kLeavingtrucksFieldNumber = 1;
  ::UA::TruckDst* mutable_leavingtrucks(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >*
      mutable_leavingtrucks();
  const ::UA::TruckDst& leavingtrucks(int index) const;
  ::UA::TruckDst* add_leavingtrucks();
  const ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >&
      leavingtrucks() const;

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.DetermineDst)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::TruckDst > leavingtrucks_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class TruckDst :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.TruckDst) */ {
 public:
  TruckDst();
  virtual ~TruckDst();

  TruckDst(const TruckDst& from);

  inline TruckDst& operator=(const TruckDst& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TruckDst(TruckDst&& from) noexcept
    : TruckDst() {
    *this = ::std::move(from);
  }

  inline TruckDst& operator=(TruckDst&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TruckDst& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TruckDst* internal_default_instance() {
    return reinterpret_cast<const TruckDst*>(
               &_TruckDst_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(TruckDst* other);
  friend void swap(TruckDst& a, TruckDst& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TruckDst* New() const final {
    return CreateMaybeMessage<TruckDst>(nullptr);
  }

  TruckDst* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TruckDst>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TruckDst& from);
  void MergeFrom(const TruckDst& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TruckDst* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int64 shipid = 4;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 4;
  ::google::protobuf::int64 shipid() const;
  void set_shipid(::google::protobuf::int64 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.TruckDst)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int64 shipid_;
  ::google::protobuf::int32 y_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class SettleShipment :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.SettleShipment) */ {
 public:
  SettleShipment();
  virtual ~SettleShipment();

  SettleShipment(const SettleShipment& from);

  inline SettleShipment& operator=(const SettleShipment& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SettleShipment(SettleShipment&& from) noexcept
    : SettleShipment() {
    *this = ::std::move(from);
  }

  inline SettleShipment& operator=(SettleShipment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SettleShipment& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SettleShipment* internal_default_instance() {
    return reinterpret_cast<const SettleShipment*>(
               &_SettleShipment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(SettleShipment* other);
  friend void swap(SettleShipment& a, SettleShipment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SettleShipment* New() const final {
    return CreateMaybeMessage<SettleShipment>(nullptr);
  }

  SettleShipment* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SettleShipment>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SettleShipment& from);
  void MergeFrom(const SettleShipment& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SettleShipment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.PackageInfo packages = 1;
  int packages_size() const;
  void clear_packages();
  static const int kPackagesFieldNumber = 1;
  ::UA::PackageInfo* mutable_packages(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::PackageInfo >*
      mutable_packages();
  const ::UA::PackageInfo& packages(int index) const;
  ::UA::PackageInfo* add_packages();
  const ::google::protobuf::RepeatedPtrField< ::UA::PackageInfo >&
      packages() const;

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.SettleShipment)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::PackageInfo > packages_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class PackageInfo :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.PackageInfo) */ {
 public:
  PackageInfo();
  virtual ~PackageInfo();

  PackageInfo(const PackageInfo& from);

  inline PackageInfo& operator=(const PackageInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PackageInfo(PackageInfo&& from) noexcept
    : PackageInfo() {
    *this = ::std::move(from);
  }

  inline PackageInfo& operator=(PackageInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PackageInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PackageInfo* internal_default_instance() {
    return reinterpret_cast<const PackageInfo*>(
               &_PackageInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(PackageInfo* other);
  friend void swap(PackageInfo& a, PackageInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PackageInfo* New() const final {
    return CreateMaybeMessage<PackageInfo>(nullptr);
  }

  PackageInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PackageInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PackageInfo& from);
  void MergeFrom(const PackageInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PackageInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string description = 2;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // required int64 packageid = 1;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 shipid = 4;
  bool has_shipid() const;
  void clear_shipid();
  static const int kShipidFieldNumber = 4;
  ::google::protobuf::int64 shipid() const;
  void set_shipid(::google::protobuf::int64 value);

  // required int32 count = 3;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 3;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.PackageInfo)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 shipid_;
  ::google::protobuf::int32 count_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class UCommands :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.UCommands) */ {
 public:
  UCommands();
  virtual ~UCommands();

  UCommands(const UCommands& from);

  inline UCommands& operator=(const UCommands& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UCommands(UCommands&& from) noexcept
    : UCommands() {
    *this = ::std::move(from);
  }

  inline UCommands& operator=(UCommands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const UCommands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UCommands* internal_default_instance() {
    return reinterpret_cast<const UCommands*>(
               &_UCommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(UCommands* other);
  friend void swap(UCommands& a, UCommands& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UCommands* New() const final {
    return CreateMaybeMessage<UCommands>(nullptr);
  }

  UCommands* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UCommands>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UCommands& from);
  void MergeFrom(const UCommands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.InitWorld worlds = 1;
  int worlds_size() const;
  void clear_worlds();
  static const int kWorldsFieldNumber = 1;
  ::UA::InitWorld* mutable_worlds(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >*
      mutable_worlds();
  const ::UA::InitWorld& worlds(int index) const;
  ::UA::InitWorld* add_worlds();
  const ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >&
      worlds() const;

  // repeated .UA.DetermineTruck trucks = 2;
  int trucks_size() const;
  void clear_trucks();
  static const int kTrucksFieldNumber = 2;
  ::UA::DetermineTruck* mutable_trucks(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >*
      mutable_trucks();
  const ::UA::DetermineTruck& trucks(int index) const;
  ::UA::DetermineTruck* add_trucks();
  const ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >&
      trucks() const;

  // repeated .UA.SettleShipment shipments = 3;
  int shipments_size() const;
  void clear_shipments();
  static const int kShipmentsFieldNumber = 3;
  ::UA::SettleShipment* mutable_shipments(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >*
      mutable_shipments();
  const ::UA::SettleShipment& shipments(int index) const;
  ::UA::SettleShipment* add_shipments();
  const ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >&
      shipments() const;

  // @@protoc_insertion_point(class_scope:UA.UCommands)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::InitWorld > worlds_;
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck > trucks_;
  ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment > shipments_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class ACommands :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.ACommands) */ {
 public:
  ACommands();
  virtual ~ACommands();

  ACommands(const ACommands& from);

  inline ACommands& operator=(const ACommands& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ACommands(ACommands&& from) noexcept
    : ACommands() {
    *this = ::std::move(from);
  }

  inline ACommands& operator=(ACommands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ACommands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ACommands* internal_default_instance() {
    return reinterpret_cast<const ACommands*>(
               &_ACommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(ACommands* other);
  friend void swap(ACommands& a, ACommands& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ACommands* New() const final {
    return CreateMaybeMessage<ACommands>(nullptr);
  }

  ACommands* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ACommands>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ACommands& from);
  void MergeFrom(const ACommands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ACommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.DetermineWarehouse warehouses = 1;
  int warehouses_size() const;
  void clear_warehouses();
  static const int kWarehousesFieldNumber = 1;
  ::UA::DetermineWarehouse* mutable_warehouses(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >*
      mutable_warehouses();
  const ::UA::DetermineWarehouse& warehouses(int index) const;
  ::UA::DetermineWarehouse* add_warehouses();
  const ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >&
      warehouses() const;

  // repeated .UA.DetermineDst dests = 2;
  int dests_size() const;
  void clear_dests();
  static const int kDestsFieldNumber = 2;
  ::UA::DetermineDst* mutable_dests(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >*
      mutable_dests();
  const ::UA::DetermineDst& dests(int index) const;
  ::UA::DetermineDst* add_dests();
  const ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >&
      dests() const;

  // @@protoc_insertion_point(class_scope:UA.ACommands)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse > warehouses_;
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst > dests_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class Response :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    11;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required bool succeed = 1;
  bool has_succeed() const;
  void clear_succeed();
  static const int kSucceedFieldNumber = 1;
  bool succeed() const;
  void set_succeed(bool value);

  // @@protoc_insertion_point(class_scope:UA.Response)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 seqnum_;
  bool succeed_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InitWorld

// required int64 worldid = 1;
inline bool InitWorld::has_worldid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InitWorld::clear_worldid() {
  worldid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 InitWorld::worldid() const {
  // @@protoc_insertion_point(field_get:UA.InitWorld.worldid)
  return worldid_;
}
inline void InitWorld::set_worldid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  worldid_ = value;
  // @@protoc_insertion_point(field_set:UA.InitWorld.worldid)
}

// required int64 seqnum = 2;
inline bool InitWorld::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InitWorld::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 InitWorld::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.InitWorld.seqnum)
  return seqnum_;
}
inline void InitWorld::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.InitWorld.seqnum)
}

// -------------------------------------------------------------------

// WarehouseInfo

// required int32 whid = 1;
inline bool WarehouseInfo::has_whid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void WarehouseInfo::clear_whid() {
  whid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 WarehouseInfo::whid() const {
  // @@protoc_insertion_point(field_get:UA.WarehouseInfo.whid)
  return whid_;
}
inline void WarehouseInfo::set_whid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  whid_ = value;
  // @@protoc_insertion_point(field_set:UA.WarehouseInfo.whid)
}

// required int32 wh_x = 2;
inline bool WarehouseInfo::has_wh_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void WarehouseInfo::clear_wh_x() {
  wh_x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 WarehouseInfo::wh_x() const {
  // @@protoc_insertion_point(field_get:UA.WarehouseInfo.wh_x)
  return wh_x_;
}
inline void WarehouseInfo::set_wh_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  wh_x_ = value;
  // @@protoc_insertion_point(field_set:UA.WarehouseInfo.wh_x)
}

// required int32 wh_y = 3;
inline bool WarehouseInfo::has_wh_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void WarehouseInfo::clear_wh_y() {
  wh_y_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 WarehouseInfo::wh_y() const {
  // @@protoc_insertion_point(field_get:UA.WarehouseInfo.wh_y)
  return wh_y_;
}
inline void WarehouseInfo::set_wh_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  wh_y_ = value;
  // @@protoc_insertion_point(field_set:UA.WarehouseInfo.wh_y)
}

// -------------------------------------------------------------------

// DetermineWarehouse

// repeated .UA.WarehouseInfo warehouses = 1;
inline int DetermineWarehouse::warehouses_size() const {
  return warehouses_.size();
}
inline void DetermineWarehouse::clear_warehouses() {
  warehouses_.Clear();
}
inline ::UA::WarehouseInfo* DetermineWarehouse::mutable_warehouses(int index) {
  // @@protoc_insertion_point(field_mutable:UA.DetermineWarehouse.warehouses)
  return warehouses_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::WarehouseInfo >*
DetermineWarehouse::mutable_warehouses() {
  // @@protoc_insertion_point(field_mutable_list:UA.DetermineWarehouse.warehouses)
  return &warehouses_;
}
inline const ::UA::WarehouseInfo& DetermineWarehouse::warehouses(int index) const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.warehouses)
  return warehouses_.Get(index);
}
inline ::UA::WarehouseInfo* DetermineWarehouse::add_warehouses() {
  // @@protoc_insertion_point(field_add:UA.DetermineWarehouse.warehouses)
  return warehouses_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::WarehouseInfo >&
DetermineWarehouse::warehouses() const {
  // @@protoc_insertion_point(field_list:UA.DetermineWarehouse.warehouses)
  return warehouses_;
}

// required int64 seqnum = 2;
inline bool DetermineWarehouse::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetermineWarehouse::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 DetermineWarehouse::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.seqnum)
  return seqnum_;
}
inline void DetermineWarehouse::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineWarehouse.seqnum)
}

// -------------------------------------------------------------------

// DetermineTruck

// repeated .UA.TruckLocation arrivedtrucks = 1;
inline int DetermineTruck::arrivedtrucks_size() const {
  return arrivedtrucks_.size();
}
inline void DetermineTruck::clear_arrivedtrucks() {
  arrivedtrucks_.Clear();
}
inline ::UA::TruckLocation* DetermineTruck::mutable_arrivedtrucks(int index) {
  // @@protoc_insertion_point(field_mutable:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >*
DetermineTruck::mutable_arrivedtrucks() {
  // @@protoc_insertion_point(field_mutable_list:UA.DetermineTruck.arrivedtrucks)
  return &arrivedtrucks_;
}
inline const ::UA::TruckLocation& DetermineTruck::arrivedtrucks(int index) const {
  // @@protoc_insertion_point(field_get:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_.Get(index);
}
inline ::UA::TruckLocation* DetermineTruck::add_arrivedtrucks() {
  // @@protoc_insertion_point(field_add:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >&
DetermineTruck::arrivedtrucks() const {
  // @@protoc_insertion_point(field_list:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_;
}

// required int64 seqnum = 2;
inline bool DetermineTruck::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetermineTruck::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 DetermineTruck::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.DetermineTruck.seqnum)
  return seqnum_;
}
inline void DetermineTruck::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineTruck.seqnum)
}

// -------------------------------------------------------------------

// TruckLocation

// required int32 truckid = 1;
inline bool TruckLocation::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TruckLocation::clear_truckid() {
  truckid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 TruckLocation::truckid() const {
  // @@protoc_insertion_point(field_get:UA.TruckLocation.truckid)
  return truckid_;
}
inline void TruckLocation::set_truckid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckLocation.truckid)
}

// required int32 whid = 2;
inline bool TruckLocation::has_whid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TruckLocation::clear_whid() {
  whid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 TruckLocation::whid() const {
  // @@protoc_insertion_point(field_get:UA.TruckLocation.whid)
  return whid_;
}
inline void TruckLocation::set_whid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  whid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckLocation.whid)
}

// -------------------------------------------------------------------

// DetermineDst

// repeated .UA.TruckDst leavingtrucks = 1;
inline int DetermineDst::leavingtrucks_size() const {
  return leavingtrucks_.size();
}
inline void DetermineDst::clear_leavingtrucks() {
  leavingtrucks_.Clear();
}
inline ::UA::TruckDst* DetermineDst::mutable_leavingtrucks(int index) {
  // @@protoc_insertion_point(field_mutable:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >*
DetermineDst::mutable_leavingtrucks() {
  // @@protoc_insertion_point(field_mutable_list:UA.DetermineDst.leavingtrucks)
  return &leavingtrucks_;
}
inline const ::UA::TruckDst& DetermineDst::leavingtrucks(int index) const {
  // @@protoc_insertion_point(field_get:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_.Get(index);
}
inline ::UA::TruckDst* DetermineDst::add_leavingtrucks() {
  // @@protoc_insertion_point(field_add:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >&
DetermineDst::leavingtrucks() const {
  // @@protoc_insertion_point(field_list:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_;
}

// required int64 seqnum = 2;
inline bool DetermineDst::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetermineDst::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 DetermineDst::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.DetermineDst.seqnum)
  return seqnum_;
}
inline void DetermineDst::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineDst.seqnum)
}

// -------------------------------------------------------------------

// TruckDst

// required int32 truckid = 1;
inline bool TruckDst::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TruckDst::clear_truckid() {
  truckid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 TruckDst::truckid() const {
  // @@protoc_insertion_point(field_get:UA.TruckDst.truckid)
  return truckid_;
}
inline void TruckDst::set_truckid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckDst.truckid)
}

// required int32 x = 2;
inline bool TruckDst::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TruckDst::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 TruckDst::x() const {
  // @@protoc_insertion_point(field_get:UA.TruckDst.x)
  return x_;
}
inline void TruckDst::set_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  x_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckDst.x)
}

// required int32 y = 3;
inline bool TruckDst::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TruckDst::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 TruckDst::y() const {
  // @@protoc_insertion_point(field_get:UA.TruckDst.y)
  return y_;
}
inline void TruckDst::set_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  y_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckDst.y)
}

// required int64 shipid = 4;
inline bool TruckDst::has_shipid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TruckDst::clear_shipid() {
  shipid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 TruckDst::shipid() const {
  // @@protoc_insertion_point(field_get:UA.TruckDst.shipid)
  return shipid_;
}
inline void TruckDst::set_shipid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  shipid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckDst.shipid)
}

// -------------------------------------------------------------------

// SettleShipment

// repeated .UA.PackageInfo packages = 1;
inline int SettleShipment::packages_size() const {
  return packages_.size();
}
inline void SettleShipment::clear_packages() {
  packages_.Clear();
}
inline ::UA::PackageInfo* SettleShipment::mutable_packages(int index) {
  // @@protoc_insertion_point(field_mutable:UA.SettleShipment.packages)
  return packages_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::PackageInfo >*
SettleShipment::mutable_packages() {
  // @@protoc_insertion_point(field_mutable_list:UA.SettleShipment.packages)
  return &packages_;
}
inline const ::UA::PackageInfo& SettleShipment::packages(int index) const {
  // @@protoc_insertion_point(field_get:UA.SettleShipment.packages)
  return packages_.Get(index);
}
inline ::UA::PackageInfo* SettleShipment::add_packages() {
  // @@protoc_insertion_point(field_add:UA.SettleShipment.packages)
  return packages_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::PackageInfo >&
SettleShipment::packages() const {
  // @@protoc_insertion_point(field_list:UA.SettleShipment.packages)
  return packages_;
}

// required int64 seqnum = 2;
inline bool SettleShipment::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SettleShipment::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 SettleShipment::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.SettleShipment.seqnum)
  return seqnum_;
}
inline void SettleShipment::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.SettleShipment.seqnum)
}

// -------------------------------------------------------------------

// PackageInfo

// required int64 packageid = 1;
inline bool PackageInfo::has_packageid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PackageInfo::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 PackageInfo::packageid() const {
  // @@protoc_insertion_point(field_get:UA.PackageInfo.packageid)
  return packageid_;
}
inline void PackageInfo::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:UA.PackageInfo.packageid)
}

// required string description = 2;
inline bool PackageInfo::has_description() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PackageInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& PackageInfo::description() const {
  // @@protoc_insertion_point(field_get:UA.PackageInfo.description)
  return description_.GetNoArena();
}
inline void PackageInfo::set_description(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UA.PackageInfo.description)
}
#if LANG_CXX11
inline void PackageInfo::set_description(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UA.PackageInfo.description)
}
#endif
inline void PackageInfo::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UA.PackageInfo.description)
}
inline void PackageInfo::set_description(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UA.PackageInfo.description)
}
inline ::std::string* PackageInfo::mutable_description() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:UA.PackageInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PackageInfo::release_description() {
  // @@protoc_insertion_point(field_release:UA.PackageInfo.description)
  if (!has_description()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return description_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PackageInfo::set_allocated_description(::std::string* description) {
  if (description != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:UA.PackageInfo.description)
}

// required int32 count = 3;
inline bool PackageInfo::has_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PackageInfo::clear_count() {
  count_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 PackageInfo::count() const {
  // @@protoc_insertion_point(field_get:UA.PackageInfo.count)
  return count_;
}
inline void PackageInfo::set_count(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  count_ = value;
  // @@protoc_insertion_point(field_set:UA.PackageInfo.count)
}

// required int64 shipid = 4;
inline bool PackageInfo::has_shipid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PackageInfo::clear_shipid() {
  shipid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 PackageInfo::shipid() const {
  // @@protoc_insertion_point(field_get:UA.PackageInfo.shipid)
  return shipid_;
}
inline void PackageInfo::set_shipid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  shipid_ = value;
  // @@protoc_insertion_point(field_set:UA.PackageInfo.shipid)
}

// -------------------------------------------------------------------

// UCommands

// repeated .UA.InitWorld worlds = 1;
inline int UCommands::worlds_size() const {
  return worlds_.size();
}
inline void UCommands::clear_worlds() {
  worlds_.Clear();
}
inline ::UA::InitWorld* UCommands::mutable_worlds(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UCommands.worlds)
  return worlds_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >*
UCommands::mutable_worlds() {
  // @@protoc_insertion_point(field_mutable_list:UA.UCommands.worlds)
  return &worlds_;
}
inline const ::UA::InitWorld& UCommands::worlds(int index) const {
  // @@protoc_insertion_point(field_get:UA.UCommands.worlds)
  return worlds_.Get(index);
}
inline ::UA::InitWorld* UCommands::add_worlds() {
  // @@protoc_insertion_point(field_add:UA.UCommands.worlds)
  return worlds_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >&
UCommands::worlds() const {
  // @@protoc_insertion_point(field_list:UA.UCommands.worlds)
  return worlds_;
}

// repeated .UA.DetermineTruck trucks = 2;
inline int UCommands::trucks_size() const {
  return trucks_.size();
}
inline void UCommands::clear_trucks() {
  trucks_.Clear();
}
inline ::UA::DetermineTruck* UCommands::mutable_trucks(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UCommands.trucks)
  return trucks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >*
UCommands::mutable_trucks() {
  // @@protoc_insertion_point(field_mutable_list:UA.UCommands.trucks)
  return &trucks_;
}
inline const ::UA::DetermineTruck& UCommands::trucks(int index) const {
  // @@protoc_insertion_point(field_get:UA.UCommands.trucks)
  return trucks_.Get(index);
}
inline ::UA::DetermineTruck* UCommands::add_trucks() {
  // @@protoc_insertion_point(field_add:UA.UCommands.trucks)
  return trucks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >&
UCommands::trucks() const {
  // @@protoc_insertion_point(field_list:UA.UCommands.trucks)
  return trucks_;
}

// repeated .UA.SettleShipment shipments = 3;
inline int UCommands::shipments_size() const {
  return shipments_.size();
}
inline void UCommands::clear_shipments() {
  shipments_.Clear();
}
inline ::UA::SettleShipment* UCommands::mutable_shipments(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UCommands.shipments)
  return shipments_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >*
UCommands::mutable_shipments() {
  // @@protoc_insertion_point(field_mutable_list:UA.UCommands.shipments)
  return &shipments_;
}
inline const ::UA::SettleShipment& UCommands::shipments(int index) const {
  // @@protoc_insertion_point(field_get:UA.UCommands.shipments)
  return shipments_.Get(index);
}
inline ::UA::SettleShipment* UCommands::add_shipments() {
  // @@protoc_insertion_point(field_add:UA.UCommands.shipments)
  return shipments_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >&
UCommands::shipments() const {
  // @@protoc_insertion_point(field_list:UA.UCommands.shipments)
  return shipments_;
}

// -------------------------------------------------------------------

// ACommands

// repeated .UA.DetermineWarehouse warehouses = 1;
inline int ACommands::warehouses_size() const {
  return warehouses_.size();
}
inline void ACommands::clear_warehouses() {
  warehouses_.Clear();
}
inline ::UA::DetermineWarehouse* ACommands::mutable_warehouses(int index) {
  // @@protoc_insertion_point(field_mutable:UA.ACommands.warehouses)
  return warehouses_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >*
ACommands::mutable_warehouses() {
  // @@protoc_insertion_point(field_mutable_list:UA.ACommands.warehouses)
  return &warehouses_;
}
inline const ::UA::DetermineWarehouse& ACommands::warehouses(int index) const {
  // @@protoc_insertion_point(field_get:UA.ACommands.warehouses)
  return warehouses_.Get(index);
}
inline ::UA::DetermineWarehouse* ACommands::add_warehouses() {
  // @@protoc_insertion_point(field_add:UA.ACommands.warehouses)
  return warehouses_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >&
ACommands::warehouses() const {
  // @@protoc_insertion_point(field_list:UA.ACommands.warehouses)
  return warehouses_;
}

// repeated .UA.DetermineDst dests = 2;
inline int ACommands::dests_size() const {
  return dests_.size();
}
inline void ACommands::clear_dests() {
  dests_.Clear();
}
inline ::UA::DetermineDst* ACommands::mutable_dests(int index) {
  // @@protoc_insertion_point(field_mutable:UA.ACommands.dests)
  return dests_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >*
ACommands::mutable_dests() {
  // @@protoc_insertion_point(field_mutable_list:UA.ACommands.dests)
  return &dests_;
}
inline const ::UA::DetermineDst& ACommands::dests(int index) const {
  // @@protoc_insertion_point(field_get:UA.ACommands.dests)
  return dests_.Get(index);
}
inline ::UA::DetermineDst* ACommands::add_dests() {
  // @@protoc_insertion_point(field_add:UA.ACommands.dests)
  return dests_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >&
ACommands::dests() const {
  // @@protoc_insertion_point(field_list:UA.ACommands.dests)
  return dests_;
}

// -------------------------------------------------------------------

// Response

// required bool succeed = 1;
inline bool Response::has_succeed() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Response::clear_succeed() {
  succeed_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool Response::succeed() const {
  // @@protoc_insertion_point(field_get:UA.Response.succeed)
  return succeed_;
}
inline void Response::set_succeed(bool value) {
  _has_bits_[0] |= 0x00000002u;
  succeed_ = value;
  // @@protoc_insertion_point(field_set:UA.Response.succeed)
}

// required int64 seqnum = 2;
inline bool Response::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Response::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 Response::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.Response.seqnum)
  return seqnum_;
}
inline void Response::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.Response.seqnum)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace UA

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ups_5famazon_2eproto
