// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ups_amazon.proto

#ifndef PROTOBUF_INCLUDED_ups_5famazon_2eproto
#define PROTOBUF_INCLUDED_ups_5famazon_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ups_5famazon_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ups_5famazon_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ups_5famazon_2eproto();
namespace UA {
class APackageInfo;
class APackageInfoDefaultTypeInternal;
extern APackageInfoDefaultTypeInternal _APackageInfo_default_instance_;
class AUCommands;
class AUCommandsDefaultTypeInternal;
extern AUCommandsDefaultTypeInternal _AUCommands_default_instance_;
class DetermineDst;
class DetermineDstDefaultTypeInternal;
extern DetermineDstDefaultTypeInternal _DetermineDst_default_instance_;
class DetermineTruck;
class DetermineTruckDefaultTypeInternal;
extern DetermineTruckDefaultTypeInternal _DetermineTruck_default_instance_;
class DetermineWarehouse;
class DetermineWarehouseDefaultTypeInternal;
extern DetermineWarehouseDefaultTypeInternal _DetermineWarehouse_default_instance_;
class FinishShipment;
class FinishShipmentDefaultTypeInternal;
extern FinishShipmentDefaultTypeInternal _FinishShipment_default_instance_;
class InitWorld;
class InitWorldDefaultTypeInternal;
extern InitWorldDefaultTypeInternal _InitWorld_default_instance_;
class SettleShipment;
class SettleShipmentDefaultTypeInternal;
extern SettleShipmentDefaultTypeInternal _SettleShipment_default_instance_;
class TruckDst;
class TruckDstDefaultTypeInternal;
extern TruckDstDefaultTypeInternal _TruckDst_default_instance_;
class TruckLocation;
class TruckLocationDefaultTypeInternal;
extern TruckLocationDefaultTypeInternal _TruckLocation_default_instance_;
class UACommands;
class UACommandsDefaultTypeInternal;
extern UACommandsDefaultTypeInternal _UACommands_default_instance_;
}  // namespace UA
namespace google {
namespace protobuf {
template<> ::UA::APackageInfo* Arena::CreateMaybeMessage<::UA::APackageInfo>(Arena*);
template<> ::UA::AUCommands* Arena::CreateMaybeMessage<::UA::AUCommands>(Arena*);
template<> ::UA::DetermineDst* Arena::CreateMaybeMessage<::UA::DetermineDst>(Arena*);
template<> ::UA::DetermineTruck* Arena::CreateMaybeMessage<::UA::DetermineTruck>(Arena*);
template<> ::UA::DetermineWarehouse* Arena::CreateMaybeMessage<::UA::DetermineWarehouse>(Arena*);
template<> ::UA::FinishShipment* Arena::CreateMaybeMessage<::UA::FinishShipment>(Arena*);
template<> ::UA::InitWorld* Arena::CreateMaybeMessage<::UA::InitWorld>(Arena*);
template<> ::UA::SettleShipment* Arena::CreateMaybeMessage<::UA::SettleShipment>(Arena*);
template<> ::UA::TruckDst* Arena::CreateMaybeMessage<::UA::TruckDst>(Arena*);
template<> ::UA::TruckLocation* Arena::CreateMaybeMessage<::UA::TruckLocation>(Arena*);
template<> ::UA::UACommands* Arena::CreateMaybeMessage<::UA::UACommands>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace UA {

// ===================================================================

class InitWorld :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.InitWorld) */ {
 public:
  InitWorld();
  virtual ~InitWorld();

  InitWorld(const InitWorld& from);

  inline InitWorld& operator=(const InitWorld& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InitWorld(InitWorld&& from) noexcept
    : InitWorld() {
    *this = ::std::move(from);
  }

  inline InitWorld& operator=(InitWorld&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const InitWorld& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InitWorld* internal_default_instance() {
    return reinterpret_cast<const InitWorld*>(
               &_InitWorld_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InitWorld* other);
  friend void swap(InitWorld& a, InitWorld& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InitWorld* New() const final {
    return CreateMaybeMessage<InitWorld>(nullptr);
  }

  InitWorld* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InitWorld>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InitWorld& from);
  void MergeFrom(const InitWorld& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InitWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 worldid = 1;
  bool has_worldid() const;
  void clear_worldid();
  static const int kWorldidFieldNumber = 1;
  ::google::protobuf::int64 worldid() const;
  void set_worldid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.InitWorld)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 worldid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class APackageInfo :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.APackageInfo) */ {
 public:
  APackageInfo();
  virtual ~APackageInfo();

  APackageInfo(const APackageInfo& from);

  inline APackageInfo& operator=(const APackageInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  APackageInfo(APackageInfo&& from) noexcept
    : APackageInfo() {
    *this = ::std::move(from);
  }

  inline APackageInfo& operator=(APackageInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const APackageInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const APackageInfo* internal_default_instance() {
    return reinterpret_cast<const APackageInfo*>(
               &_APackageInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(APackageInfo* other);
  friend void swap(APackageInfo& a, APackageInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline APackageInfo* New() const final {
    return CreateMaybeMessage<APackageInfo>(nullptr);
  }

  APackageInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<APackageInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const APackageInfo& from);
  void MergeFrom(const APackageInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(APackageInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string description = 1;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 1;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // optional string upsaccount = 6;
  bool has_upsaccount() const;
  void clear_upsaccount();
  static const int kUpsaccountFieldNumber = 6;
  const ::std::string& upsaccount() const;
  void set_upsaccount(const ::std::string& value);
  #if LANG_CXX11
  void set_upsaccount(::std::string&& value);
  #endif
  void set_upsaccount(const char* value);
  void set_upsaccount(const char* value, size_t size);
  ::std::string* mutable_upsaccount();
  ::std::string* release_upsaccount();
  void set_allocated_upsaccount(::std::string* upsaccount);

  // required int64 packageid = 3;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 3;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int32 count = 2;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // required int32 x = 4;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 4;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int32 y = 5;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 5;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.APackageInfo)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr upsaccount_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int32 count_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class DetermineWarehouse :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.DetermineWarehouse) */ {
 public:
  DetermineWarehouse();
  virtual ~DetermineWarehouse();

  DetermineWarehouse(const DetermineWarehouse& from);

  inline DetermineWarehouse& operator=(const DetermineWarehouse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetermineWarehouse(DetermineWarehouse&& from) noexcept
    : DetermineWarehouse() {
    *this = ::std::move(from);
  }

  inline DetermineWarehouse& operator=(DetermineWarehouse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DetermineWarehouse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetermineWarehouse* internal_default_instance() {
    return reinterpret_cast<const DetermineWarehouse*>(
               &_DetermineWarehouse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(DetermineWarehouse* other);
  friend void swap(DetermineWarehouse& a, DetermineWarehouse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetermineWarehouse* New() const final {
    return CreateMaybeMessage<DetermineWarehouse>(nullptr);
  }

  DetermineWarehouse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetermineWarehouse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetermineWarehouse& from);
  void MergeFrom(const DetermineWarehouse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetermineWarehouse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.APackageInfo packageinfos = 4;
  int packageinfos_size() const;
  void clear_packageinfos();
  static const int kPackageinfosFieldNumber = 4;
  ::UA::APackageInfo* mutable_packageinfos(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::APackageInfo >*
      mutable_packageinfos();
  const ::UA::APackageInfo& packageinfos(int index) const;
  ::UA::APackageInfo* add_packageinfos();
  const ::google::protobuf::RepeatedPtrField< ::UA::APackageInfo >&
      packageinfos() const;

  // required int32 whid = 1;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 1;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // required int32 wh_x = 2;
  bool has_wh_x() const;
  void clear_wh_x();
  static const int kWhXFieldNumber = 2;
  ::google::protobuf::int32 wh_x() const;
  void set_wh_x(::google::protobuf::int32 value);

  // required int64 seqnum = 5;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 5;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required int32 wh_y = 3;
  bool has_wh_y() const;
  void clear_wh_y();
  static const int kWhYFieldNumber = 3;
  ::google::protobuf::int32 wh_y() const;
  void set_wh_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.DetermineWarehouse)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::APackageInfo > packageinfos_;
  ::google::protobuf::int32 whid_;
  ::google::protobuf::int32 wh_x_;
  ::google::protobuf::int64 seqnum_;
  ::google::protobuf::int32 wh_y_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class DetermineTruck :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.DetermineTruck) */ {
 public:
  DetermineTruck();
  virtual ~DetermineTruck();

  DetermineTruck(const DetermineTruck& from);

  inline DetermineTruck& operator=(const DetermineTruck& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetermineTruck(DetermineTruck&& from) noexcept
    : DetermineTruck() {
    *this = ::std::move(from);
  }

  inline DetermineTruck& operator=(DetermineTruck&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DetermineTruck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetermineTruck* internal_default_instance() {
    return reinterpret_cast<const DetermineTruck*>(
               &_DetermineTruck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DetermineTruck* other);
  friend void swap(DetermineTruck& a, DetermineTruck& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetermineTruck* New() const final {
    return CreateMaybeMessage<DetermineTruck>(nullptr);
  }

  DetermineTruck* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetermineTruck>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetermineTruck& from);
  void MergeFrom(const DetermineTruck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetermineTruck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.TruckLocation arrivedtrucks = 1;
  int arrivedtrucks_size() const;
  void clear_arrivedtrucks();
  static const int kArrivedtrucksFieldNumber = 1;
  ::UA::TruckLocation* mutable_arrivedtrucks(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >*
      mutable_arrivedtrucks();
  const ::UA::TruckLocation& arrivedtrucks(int index) const;
  ::UA::TruckLocation* add_arrivedtrucks();
  const ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >&
      arrivedtrucks() const;

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.DetermineTruck)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation > arrivedtrucks_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class TruckLocation :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.TruckLocation) */ {
 public:
  TruckLocation();
  virtual ~TruckLocation();

  TruckLocation(const TruckLocation& from);

  inline TruckLocation& operator=(const TruckLocation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TruckLocation(TruckLocation&& from) noexcept
    : TruckLocation() {
    *this = ::std::move(from);
  }

  inline TruckLocation& operator=(TruckLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TruckLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TruckLocation* internal_default_instance() {
    return reinterpret_cast<const TruckLocation*>(
               &_TruckLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(TruckLocation* other);
  friend void swap(TruckLocation& a, TruckLocation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TruckLocation* New() const final {
    return CreateMaybeMessage<TruckLocation>(nullptr);
  }

  TruckLocation* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TruckLocation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TruckLocation& from);
  void MergeFrom(const TruckLocation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TruckLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int32 wh_x = 2;
  bool has_wh_x() const;
  void clear_wh_x();
  static const int kWhXFieldNumber = 2;
  ::google::protobuf::int32 wh_x() const;
  void set_wh_x(::google::protobuf::int32 value);

  // required int32 wh_y = 3;
  bool has_wh_y() const;
  void clear_wh_y();
  static const int kWhYFieldNumber = 3;
  ::google::protobuf::int32 wh_y() const;
  void set_wh_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.TruckLocation)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int32 wh_x_;
  ::google::protobuf::int32 wh_y_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class DetermineDst :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.DetermineDst) */ {
 public:
  DetermineDst();
  virtual ~DetermineDst();

  DetermineDst(const DetermineDst& from);

  inline DetermineDst& operator=(const DetermineDst& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetermineDst(DetermineDst&& from) noexcept
    : DetermineDst() {
    *this = ::std::move(from);
  }

  inline DetermineDst& operator=(DetermineDst&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DetermineDst& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetermineDst* internal_default_instance() {
    return reinterpret_cast<const DetermineDst*>(
               &_DetermineDst_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(DetermineDst* other);
  friend void swap(DetermineDst& a, DetermineDst& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetermineDst* New() const final {
    return CreateMaybeMessage<DetermineDst>(nullptr);
  }

  DetermineDst* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DetermineDst>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DetermineDst& from);
  void MergeFrom(const DetermineDst& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DetermineDst* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.TruckDst leavingtrucks = 1;
  int leavingtrucks_size() const;
  void clear_leavingtrucks();
  static const int kLeavingtrucksFieldNumber = 1;
  ::UA::TruckDst* mutable_leavingtrucks(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >*
      mutable_leavingtrucks();
  const ::UA::TruckDst& leavingtrucks(int index) const;
  ::UA::TruckDst* add_leavingtrucks();
  const ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >&
      leavingtrucks() const;

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.DetermineDst)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::TruckDst > leavingtrucks_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class TruckDst :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.TruckDst) */ {
 public:
  TruckDst();
  virtual ~TruckDst();

  TruckDst(const TruckDst& from);

  inline TruckDst& operator=(const TruckDst& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TruckDst(TruckDst&& from) noexcept
    : TruckDst() {
    *this = ::std::move(from);
  }

  inline TruckDst& operator=(TruckDst&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TruckDst& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TruckDst* internal_default_instance() {
    return reinterpret_cast<const TruckDst*>(
               &_TruckDst_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(TruckDst* other);
  friend void swap(TruckDst& a, TruckDst& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TruckDst* New() const final {
    return CreateMaybeMessage<TruckDst>(nullptr);
  }

  TruckDst* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TruckDst>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TruckDst& from);
  void MergeFrom(const TruckDst& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TruckDst* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 2;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 2;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int32 truckid = 1;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 1;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:UA.TruckDst)
 private:
  class HasBitSetters;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int32 truckid_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class SettleShipment :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.SettleShipment) */ {
 public:
  SettleShipment();
  virtual ~SettleShipment();

  SettleShipment(const SettleShipment& from);

  inline SettleShipment& operator=(const SettleShipment& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SettleShipment(SettleShipment&& from) noexcept
    : SettleShipment() {
    *this = ::std::move(from);
  }

  inline SettleShipment& operator=(SettleShipment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SettleShipment& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SettleShipment* internal_default_instance() {
    return reinterpret_cast<const SettleShipment*>(
               &_SettleShipment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(SettleShipment* other);
  friend void swap(SettleShipment& a, SettleShipment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SettleShipment* New() const final {
    return CreateMaybeMessage<SettleShipment>(nullptr);
  }

  SettleShipment* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SettleShipment>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SettleShipment& from);
  void MergeFrom(const SettleShipment& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SettleShipment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 packageid = 1;
  int packageid_size() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid(int index) const;
  void set_packageid(int index, ::google::protobuf::int64 value);
  void add_packageid(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      packageid() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_packageid();

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.SettleShipment)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class FinishShipment :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.FinishShipment) */ {
 public:
  FinishShipment();
  virtual ~FinishShipment();

  FinishShipment(const FinishShipment& from);

  inline FinishShipment& operator=(const FinishShipment& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FinishShipment(FinishShipment&& from) noexcept
    : FinishShipment() {
    *this = ::std::move(from);
  }

  inline FinishShipment& operator=(FinishShipment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const FinishShipment& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FinishShipment* internal_default_instance() {
    return reinterpret_cast<const FinishShipment*>(
               &_FinishShipment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(FinishShipment* other);
  friend void swap(FinishShipment& a, FinishShipment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FinishShipment* New() const final {
    return CreateMaybeMessage<FinishShipment>(nullptr);
  }

  FinishShipment* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<FinishShipment>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const FinishShipment& from);
  void MergeFrom(const FinishShipment& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FinishShipment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 packageid = 1;
  int packageid_size() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid(int index) const;
  void set_packageid(int index, ::google::protobuf::int64 value);
  void add_packageid(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      packageid() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_packageid();

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:UA.FinishShipment)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class UACommands :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.UACommands) */ {
 public:
  UACommands();
  virtual ~UACommands();

  UACommands(const UACommands& from);

  inline UACommands& operator=(const UACommands& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UACommands(UACommands&& from) noexcept
    : UACommands() {
    *this = ::std::move(from);
  }

  inline UACommands& operator=(UACommands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const UACommands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UACommands* internal_default_instance() {
    return reinterpret_cast<const UACommands*>(
               &_UACommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(UACommands* other);
  friend void swap(UACommands& a, UACommands& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UACommands* New() const final {
    return CreateMaybeMessage<UACommands>(nullptr);
  }

  UACommands* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UACommands>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UACommands& from);
  void MergeFrom(const UACommands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UACommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.InitWorld worlds = 1;
  int worlds_size() const;
  void clear_worlds();
  static const int kWorldsFieldNumber = 1;
  ::UA::InitWorld* mutable_worlds(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >*
      mutable_worlds();
  const ::UA::InitWorld& worlds(int index) const;
  ::UA::InitWorld* add_worlds();
  const ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >&
      worlds() const;

  // repeated .UA.DetermineTruck trucks = 2;
  int trucks_size() const;
  void clear_trucks();
  static const int kTrucksFieldNumber = 2;
  ::UA::DetermineTruck* mutable_trucks(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >*
      mutable_trucks();
  const ::UA::DetermineTruck& trucks(int index) const;
  ::UA::DetermineTruck* add_trucks();
  const ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >&
      trucks() const;

  // repeated .UA.SettleShipment settled = 3;
  int settled_size() const;
  void clear_settled();
  static const int kSettledFieldNumber = 3;
  ::UA::SettleShipment* mutable_settled(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >*
      mutable_settled();
  const ::UA::SettleShipment& settled(int index) const;
  ::UA::SettleShipment* add_settled();
  const ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >&
      settled() const;

  // repeated .UA.FinishShipment finished = 4;
  int finished_size() const;
  void clear_finished();
  static const int kFinishedFieldNumber = 4;
  ::UA::FinishShipment* mutable_finished(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::FinishShipment >*
      mutable_finished();
  const ::UA::FinishShipment& finished(int index) const;
  ::UA::FinishShipment* add_finished();
  const ::google::protobuf::RepeatedPtrField< ::UA::FinishShipment >&
      finished() const;

  // repeated int64 ack = 5;
  int ack_size() const;
  void clear_ack();
  static const int kAckFieldNumber = 5;
  ::google::protobuf::int64 ack(int index) const;
  void set_ack(int index, ::google::protobuf::int64 value);
  void add_ack(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      ack() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_ack();

  // @@protoc_insertion_point(class_scope:UA.UACommands)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::InitWorld > worlds_;
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck > trucks_;
  ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment > settled_;
  ::google::protobuf::RepeatedPtrField< ::UA::FinishShipment > finished_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > ack_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// -------------------------------------------------------------------

class AUCommands :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UA.AUCommands) */ {
 public:
  AUCommands();
  virtual ~AUCommands();

  AUCommands(const AUCommands& from);

  inline AUCommands& operator=(const AUCommands& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AUCommands(AUCommands&& from) noexcept
    : AUCommands() {
    *this = ::std::move(from);
  }

  inline AUCommands& operator=(AUCommands&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AUCommands& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AUCommands* internal_default_instance() {
    return reinterpret_cast<const AUCommands*>(
               &_AUCommands_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(AUCommands* other);
  friend void swap(AUCommands& a, AUCommands& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AUCommands* New() const final {
    return CreateMaybeMessage<AUCommands>(nullptr);
  }

  AUCommands* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AUCommands>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AUCommands& from);
  void MergeFrom(const AUCommands& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AUCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .UA.DetermineWarehouse warehouses = 1;
  int warehouses_size() const;
  void clear_warehouses();
  static const int kWarehousesFieldNumber = 1;
  ::UA::DetermineWarehouse* mutable_warehouses(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >*
      mutable_warehouses();
  const ::UA::DetermineWarehouse& warehouses(int index) const;
  ::UA::DetermineWarehouse* add_warehouses();
  const ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >&
      warehouses() const;

  // repeated .UA.DetermineDst dests = 2;
  int dests_size() const;
  void clear_dests();
  static const int kDestsFieldNumber = 2;
  ::UA::DetermineDst* mutable_dests(int index);
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >*
      mutable_dests();
  const ::UA::DetermineDst& dests(int index) const;
  ::UA::DetermineDst* add_dests();
  const ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >&
      dests() const;

  // repeated int64 ack = 4;
  int ack_size() const;
  void clear_ack();
  static const int kAckFieldNumber = 4;
  ::google::protobuf::int64 ack(int index) const;
  void set_ack(int index, ::google::protobuf::int64 value);
  void add_ack(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      ack() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_ack();

  // @@protoc_insertion_point(class_scope:UA.AUCommands)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse > warehouses_;
  ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst > dests_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > ack_;
  friend struct ::TableStruct_ups_5famazon_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InitWorld

// required int64 worldid = 1;
inline bool InitWorld::has_worldid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InitWorld::clear_worldid() {
  worldid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 InitWorld::worldid() const {
  // @@protoc_insertion_point(field_get:UA.InitWorld.worldid)
  return worldid_;
}
inline void InitWorld::set_worldid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  worldid_ = value;
  // @@protoc_insertion_point(field_set:UA.InitWorld.worldid)
}

// required int64 seqnum = 2;
inline bool InitWorld::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InitWorld::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int64 InitWorld::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.InitWorld.seqnum)
  return seqnum_;
}
inline void InitWorld::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.InitWorld.seqnum)
}

// -------------------------------------------------------------------

// APackageInfo

// required string description = 1;
inline bool APackageInfo::has_description() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void APackageInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& APackageInfo::description() const {
  // @@protoc_insertion_point(field_get:UA.APackageInfo.description)
  return description_.GetNoArena();
}
inline void APackageInfo::set_description(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UA.APackageInfo.description)
}
#if LANG_CXX11
inline void APackageInfo::set_description(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UA.APackageInfo.description)
}
#endif
inline void APackageInfo::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UA.APackageInfo.description)
}
inline void APackageInfo::set_description(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UA.APackageInfo.description)
}
inline ::std::string* APackageInfo::mutable_description() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:UA.APackageInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* APackageInfo::release_description() {
  // @@protoc_insertion_point(field_release:UA.APackageInfo.description)
  if (!has_description()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return description_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APackageInfo::set_allocated_description(::std::string* description) {
  if (description != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:UA.APackageInfo.description)
}

// required int32 count = 2;
inline bool APackageInfo::has_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void APackageInfo::clear_count() {
  count_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 APackageInfo::count() const {
  // @@protoc_insertion_point(field_get:UA.APackageInfo.count)
  return count_;
}
inline void APackageInfo::set_count(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  count_ = value;
  // @@protoc_insertion_point(field_set:UA.APackageInfo.count)
}

// required int64 packageid = 3;
inline bool APackageInfo::has_packageid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void APackageInfo::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 APackageInfo::packageid() const {
  // @@protoc_insertion_point(field_get:UA.APackageInfo.packageid)
  return packageid_;
}
inline void APackageInfo::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:UA.APackageInfo.packageid)
}

// required int32 x = 4;
inline bool APackageInfo::has_x() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void APackageInfo::clear_x() {
  x_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::google::protobuf::int32 APackageInfo::x() const {
  // @@protoc_insertion_point(field_get:UA.APackageInfo.x)
  return x_;
}
inline void APackageInfo::set_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000010u;
  x_ = value;
  // @@protoc_insertion_point(field_set:UA.APackageInfo.x)
}

// required int32 y = 5;
inline bool APackageInfo::has_y() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void APackageInfo::clear_y() {
  y_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::int32 APackageInfo::y() const {
  // @@protoc_insertion_point(field_get:UA.APackageInfo.y)
  return y_;
}
inline void APackageInfo::set_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000020u;
  y_ = value;
  // @@protoc_insertion_point(field_set:UA.APackageInfo.y)
}

// optional string upsaccount = 6;
inline bool APackageInfo::has_upsaccount() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void APackageInfo::clear_upsaccount() {
  upsaccount_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& APackageInfo::upsaccount() const {
  // @@protoc_insertion_point(field_get:UA.APackageInfo.upsaccount)
  return upsaccount_.GetNoArena();
}
inline void APackageInfo::set_upsaccount(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  upsaccount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UA.APackageInfo.upsaccount)
}
#if LANG_CXX11
inline void APackageInfo::set_upsaccount(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  upsaccount_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UA.APackageInfo.upsaccount)
}
#endif
inline void APackageInfo::set_upsaccount(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  upsaccount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UA.APackageInfo.upsaccount)
}
inline void APackageInfo::set_upsaccount(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  upsaccount_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UA.APackageInfo.upsaccount)
}
inline ::std::string* APackageInfo::mutable_upsaccount() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:UA.APackageInfo.upsaccount)
  return upsaccount_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* APackageInfo::release_upsaccount() {
  // @@protoc_insertion_point(field_release:UA.APackageInfo.upsaccount)
  if (!has_upsaccount()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return upsaccount_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void APackageInfo::set_allocated_upsaccount(::std::string* upsaccount) {
  if (upsaccount != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  upsaccount_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), upsaccount);
  // @@protoc_insertion_point(field_set_allocated:UA.APackageInfo.upsaccount)
}

// -------------------------------------------------------------------

// DetermineWarehouse

// required int32 whid = 1;
inline bool DetermineWarehouse::has_whid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetermineWarehouse::clear_whid() {
  whid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 DetermineWarehouse::whid() const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.whid)
  return whid_;
}
inline void DetermineWarehouse::set_whid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  whid_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineWarehouse.whid)
}

// required int32 wh_x = 2;
inline bool DetermineWarehouse::has_wh_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DetermineWarehouse::clear_wh_x() {
  wh_x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 DetermineWarehouse::wh_x() const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.wh_x)
  return wh_x_;
}
inline void DetermineWarehouse::set_wh_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  wh_x_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineWarehouse.wh_x)
}

// required int32 wh_y = 3;
inline bool DetermineWarehouse::has_wh_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DetermineWarehouse::clear_wh_y() {
  wh_y_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::google::protobuf::int32 DetermineWarehouse::wh_y() const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.wh_y)
  return wh_y_;
}
inline void DetermineWarehouse::set_wh_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  wh_y_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineWarehouse.wh_y)
}

// repeated .UA.APackageInfo packageinfos = 4;
inline int DetermineWarehouse::packageinfos_size() const {
  return packageinfos_.size();
}
inline void DetermineWarehouse::clear_packageinfos() {
  packageinfos_.Clear();
}
inline ::UA::APackageInfo* DetermineWarehouse::mutable_packageinfos(int index) {
  // @@protoc_insertion_point(field_mutable:UA.DetermineWarehouse.packageinfos)
  return packageinfos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::APackageInfo >*
DetermineWarehouse::mutable_packageinfos() {
  // @@protoc_insertion_point(field_mutable_list:UA.DetermineWarehouse.packageinfos)
  return &packageinfos_;
}
inline const ::UA::APackageInfo& DetermineWarehouse::packageinfos(int index) const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.packageinfos)
  return packageinfos_.Get(index);
}
inline ::UA::APackageInfo* DetermineWarehouse::add_packageinfos() {
  // @@protoc_insertion_point(field_add:UA.DetermineWarehouse.packageinfos)
  return packageinfos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::APackageInfo >&
DetermineWarehouse::packageinfos() const {
  // @@protoc_insertion_point(field_list:UA.DetermineWarehouse.packageinfos)
  return packageinfos_;
}

// required int64 seqnum = 5;
inline bool DetermineWarehouse::has_seqnum() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DetermineWarehouse::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int64 DetermineWarehouse::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.DetermineWarehouse.seqnum)
  return seqnum_;
}
inline void DetermineWarehouse::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineWarehouse.seqnum)
}

// -------------------------------------------------------------------

// DetermineTruck

// repeated .UA.TruckLocation arrivedtrucks = 1;
inline int DetermineTruck::arrivedtrucks_size() const {
  return arrivedtrucks_.size();
}
inline void DetermineTruck::clear_arrivedtrucks() {
  arrivedtrucks_.Clear();
}
inline ::UA::TruckLocation* DetermineTruck::mutable_arrivedtrucks(int index) {
  // @@protoc_insertion_point(field_mutable:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >*
DetermineTruck::mutable_arrivedtrucks() {
  // @@protoc_insertion_point(field_mutable_list:UA.DetermineTruck.arrivedtrucks)
  return &arrivedtrucks_;
}
inline const ::UA::TruckLocation& DetermineTruck::arrivedtrucks(int index) const {
  // @@protoc_insertion_point(field_get:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_.Get(index);
}
inline ::UA::TruckLocation* DetermineTruck::add_arrivedtrucks() {
  // @@protoc_insertion_point(field_add:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::TruckLocation >&
DetermineTruck::arrivedtrucks() const {
  // @@protoc_insertion_point(field_list:UA.DetermineTruck.arrivedtrucks)
  return arrivedtrucks_;
}

// required int64 seqnum = 2;
inline bool DetermineTruck::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetermineTruck::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 DetermineTruck::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.DetermineTruck.seqnum)
  return seqnum_;
}
inline void DetermineTruck::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineTruck.seqnum)
}

// -------------------------------------------------------------------

// TruckLocation

// required int32 truckid = 1;
inline bool TruckLocation::has_truckid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TruckLocation::clear_truckid() {
  truckid_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int32 TruckLocation::truckid() const {
  // @@protoc_insertion_point(field_get:UA.TruckLocation.truckid)
  return truckid_;
}
inline void TruckLocation::set_truckid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckLocation.truckid)
}

// required int32 wh_x = 2;
inline bool TruckLocation::has_wh_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TruckLocation::clear_wh_x() {
  wh_x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 TruckLocation::wh_x() const {
  // @@protoc_insertion_point(field_get:UA.TruckLocation.wh_x)
  return wh_x_;
}
inline void TruckLocation::set_wh_x(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  wh_x_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckLocation.wh_x)
}

// required int32 wh_y = 3;
inline bool TruckLocation::has_wh_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TruckLocation::clear_wh_y() {
  wh_y_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::int32 TruckLocation::wh_y() const {
  // @@protoc_insertion_point(field_get:UA.TruckLocation.wh_y)
  return wh_y_;
}
inline void TruckLocation::set_wh_y(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  wh_y_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckLocation.wh_y)
}

// -------------------------------------------------------------------

// DetermineDst

// repeated .UA.TruckDst leavingtrucks = 1;
inline int DetermineDst::leavingtrucks_size() const {
  return leavingtrucks_.size();
}
inline void DetermineDst::clear_leavingtrucks() {
  leavingtrucks_.Clear();
}
inline ::UA::TruckDst* DetermineDst::mutable_leavingtrucks(int index) {
  // @@protoc_insertion_point(field_mutable:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >*
DetermineDst::mutable_leavingtrucks() {
  // @@protoc_insertion_point(field_mutable_list:UA.DetermineDst.leavingtrucks)
  return &leavingtrucks_;
}
inline const ::UA::TruckDst& DetermineDst::leavingtrucks(int index) const {
  // @@protoc_insertion_point(field_get:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_.Get(index);
}
inline ::UA::TruckDst* DetermineDst::add_leavingtrucks() {
  // @@protoc_insertion_point(field_add:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::TruckDst >&
DetermineDst::leavingtrucks() const {
  // @@protoc_insertion_point(field_list:UA.DetermineDst.leavingtrucks)
  return leavingtrucks_;
}

// required int64 seqnum = 2;
inline bool DetermineDst::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DetermineDst::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 DetermineDst::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.DetermineDst.seqnum)
  return seqnum_;
}
inline void DetermineDst::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.DetermineDst.seqnum)
}

// -------------------------------------------------------------------

// TruckDst

// required int32 truckid = 1;
inline bool TruckDst::has_truckid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TruckDst::clear_truckid() {
  truckid_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::google::protobuf::int32 TruckDst::truckid() const {
  // @@protoc_insertion_point(field_get:UA.TruckDst.truckid)
  return truckid_;
}
inline void TruckDst::set_truckid(::google::protobuf::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  truckid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckDst.truckid)
}

// required int64 packageid = 2;
inline bool TruckDst::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TruckDst::clear_packageid() {
  packageid_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 TruckDst::packageid() const {
  // @@protoc_insertion_point(field_get:UA.TruckDst.packageid)
  return packageid_;
}
inline void TruckDst::set_packageid(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  packageid_ = value;
  // @@protoc_insertion_point(field_set:UA.TruckDst.packageid)
}

// -------------------------------------------------------------------

// SettleShipment

// repeated int64 packageid = 1;
inline int SettleShipment::packageid_size() const {
  return packageid_.size();
}
inline void SettleShipment::clear_packageid() {
  packageid_.Clear();
}
inline ::google::protobuf::int64 SettleShipment::packageid(int index) const {
  // @@protoc_insertion_point(field_get:UA.SettleShipment.packageid)
  return packageid_.Get(index);
}
inline void SettleShipment::set_packageid(int index, ::google::protobuf::int64 value) {
  packageid_.Set(index, value);
  // @@protoc_insertion_point(field_set:UA.SettleShipment.packageid)
}
inline void SettleShipment::add_packageid(::google::protobuf::int64 value) {
  packageid_.Add(value);
  // @@protoc_insertion_point(field_add:UA.SettleShipment.packageid)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
SettleShipment::packageid() const {
  // @@protoc_insertion_point(field_list:UA.SettleShipment.packageid)
  return packageid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
SettleShipment::mutable_packageid() {
  // @@protoc_insertion_point(field_mutable_list:UA.SettleShipment.packageid)
  return &packageid_;
}

// required int64 seqnum = 2;
inline bool SettleShipment::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SettleShipment::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 SettleShipment::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.SettleShipment.seqnum)
  return seqnum_;
}
inline void SettleShipment::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.SettleShipment.seqnum)
}

// -------------------------------------------------------------------

// FinishShipment

// repeated int64 packageid = 1;
inline int FinishShipment::packageid_size() const {
  return packageid_.size();
}
inline void FinishShipment::clear_packageid() {
  packageid_.Clear();
}
inline ::google::protobuf::int64 FinishShipment::packageid(int index) const {
  // @@protoc_insertion_point(field_get:UA.FinishShipment.packageid)
  return packageid_.Get(index);
}
inline void FinishShipment::set_packageid(int index, ::google::protobuf::int64 value) {
  packageid_.Set(index, value);
  // @@protoc_insertion_point(field_set:UA.FinishShipment.packageid)
}
inline void FinishShipment::add_packageid(::google::protobuf::int64 value) {
  packageid_.Add(value);
  // @@protoc_insertion_point(field_add:UA.FinishShipment.packageid)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
FinishShipment::packageid() const {
  // @@protoc_insertion_point(field_list:UA.FinishShipment.packageid)
  return packageid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
FinishShipment::mutable_packageid() {
  // @@protoc_insertion_point(field_mutable_list:UA.FinishShipment.packageid)
  return &packageid_;
}

// required int64 seqnum = 2;
inline bool FinishShipment::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FinishShipment::clear_seqnum() {
  seqnum_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::google::protobuf::int64 FinishShipment::seqnum() const {
  // @@protoc_insertion_point(field_get:UA.FinishShipment.seqnum)
  return seqnum_;
}
inline void FinishShipment::set_seqnum(::google::protobuf::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:UA.FinishShipment.seqnum)
}

// -------------------------------------------------------------------

// UACommands

// repeated .UA.InitWorld worlds = 1;
inline int UACommands::worlds_size() const {
  return worlds_.size();
}
inline void UACommands::clear_worlds() {
  worlds_.Clear();
}
inline ::UA::InitWorld* UACommands::mutable_worlds(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UACommands.worlds)
  return worlds_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >*
UACommands::mutable_worlds() {
  // @@protoc_insertion_point(field_mutable_list:UA.UACommands.worlds)
  return &worlds_;
}
inline const ::UA::InitWorld& UACommands::worlds(int index) const {
  // @@protoc_insertion_point(field_get:UA.UACommands.worlds)
  return worlds_.Get(index);
}
inline ::UA::InitWorld* UACommands::add_worlds() {
  // @@protoc_insertion_point(field_add:UA.UACommands.worlds)
  return worlds_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::InitWorld >&
UACommands::worlds() const {
  // @@protoc_insertion_point(field_list:UA.UACommands.worlds)
  return worlds_;
}

// repeated .UA.DetermineTruck trucks = 2;
inline int UACommands::trucks_size() const {
  return trucks_.size();
}
inline void UACommands::clear_trucks() {
  trucks_.Clear();
}
inline ::UA::DetermineTruck* UACommands::mutable_trucks(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UACommands.trucks)
  return trucks_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >*
UACommands::mutable_trucks() {
  // @@protoc_insertion_point(field_mutable_list:UA.UACommands.trucks)
  return &trucks_;
}
inline const ::UA::DetermineTruck& UACommands::trucks(int index) const {
  // @@protoc_insertion_point(field_get:UA.UACommands.trucks)
  return trucks_.Get(index);
}
inline ::UA::DetermineTruck* UACommands::add_trucks() {
  // @@protoc_insertion_point(field_add:UA.UACommands.trucks)
  return trucks_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::DetermineTruck >&
UACommands::trucks() const {
  // @@protoc_insertion_point(field_list:UA.UACommands.trucks)
  return trucks_;
}

// repeated .UA.SettleShipment settled = 3;
inline int UACommands::settled_size() const {
  return settled_.size();
}
inline void UACommands::clear_settled() {
  settled_.Clear();
}
inline ::UA::SettleShipment* UACommands::mutable_settled(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UACommands.settled)
  return settled_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >*
UACommands::mutable_settled() {
  // @@protoc_insertion_point(field_mutable_list:UA.UACommands.settled)
  return &settled_;
}
inline const ::UA::SettleShipment& UACommands::settled(int index) const {
  // @@protoc_insertion_point(field_get:UA.UACommands.settled)
  return settled_.Get(index);
}
inline ::UA::SettleShipment* UACommands::add_settled() {
  // @@protoc_insertion_point(field_add:UA.UACommands.settled)
  return settled_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::SettleShipment >&
UACommands::settled() const {
  // @@protoc_insertion_point(field_list:UA.UACommands.settled)
  return settled_;
}

// repeated .UA.FinishShipment finished = 4;
inline int UACommands::finished_size() const {
  return finished_.size();
}
inline void UACommands::clear_finished() {
  finished_.Clear();
}
inline ::UA::FinishShipment* UACommands::mutable_finished(int index) {
  // @@protoc_insertion_point(field_mutable:UA.UACommands.finished)
  return finished_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::FinishShipment >*
UACommands::mutable_finished() {
  // @@protoc_insertion_point(field_mutable_list:UA.UACommands.finished)
  return &finished_;
}
inline const ::UA::FinishShipment& UACommands::finished(int index) const {
  // @@protoc_insertion_point(field_get:UA.UACommands.finished)
  return finished_.Get(index);
}
inline ::UA::FinishShipment* UACommands::add_finished() {
  // @@protoc_insertion_point(field_add:UA.UACommands.finished)
  return finished_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::FinishShipment >&
UACommands::finished() const {
  // @@protoc_insertion_point(field_list:UA.UACommands.finished)
  return finished_;
}

// repeated int64 ack = 5;
inline int UACommands::ack_size() const {
  return ack_.size();
}
inline void UACommands::clear_ack() {
  ack_.Clear();
}
inline ::google::protobuf::int64 UACommands::ack(int index) const {
  // @@protoc_insertion_point(field_get:UA.UACommands.ack)
  return ack_.Get(index);
}
inline void UACommands::set_ack(int index, ::google::protobuf::int64 value) {
  ack_.Set(index, value);
  // @@protoc_insertion_point(field_set:UA.UACommands.ack)
}
inline void UACommands::add_ack(::google::protobuf::int64 value) {
  ack_.Add(value);
  // @@protoc_insertion_point(field_add:UA.UACommands.ack)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
UACommands::ack() const {
  // @@protoc_insertion_point(field_list:UA.UACommands.ack)
  return ack_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
UACommands::mutable_ack() {
  // @@protoc_insertion_point(field_mutable_list:UA.UACommands.ack)
  return &ack_;
}

// -------------------------------------------------------------------

// AUCommands

// repeated .UA.DetermineWarehouse warehouses = 1;
inline int AUCommands::warehouses_size() const {
  return warehouses_.size();
}
inline void AUCommands::clear_warehouses() {
  warehouses_.Clear();
}
inline ::UA::DetermineWarehouse* AUCommands::mutable_warehouses(int index) {
  // @@protoc_insertion_point(field_mutable:UA.AUCommands.warehouses)
  return warehouses_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >*
AUCommands::mutable_warehouses() {
  // @@protoc_insertion_point(field_mutable_list:UA.AUCommands.warehouses)
  return &warehouses_;
}
inline const ::UA::DetermineWarehouse& AUCommands::warehouses(int index) const {
  // @@protoc_insertion_point(field_get:UA.AUCommands.warehouses)
  return warehouses_.Get(index);
}
inline ::UA::DetermineWarehouse* AUCommands::add_warehouses() {
  // @@protoc_insertion_point(field_add:UA.AUCommands.warehouses)
  return warehouses_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::DetermineWarehouse >&
AUCommands::warehouses() const {
  // @@protoc_insertion_point(field_list:UA.AUCommands.warehouses)
  return warehouses_;
}

// repeated .UA.DetermineDst dests = 2;
inline int AUCommands::dests_size() const {
  return dests_.size();
}
inline void AUCommands::clear_dests() {
  dests_.Clear();
}
inline ::UA::DetermineDst* AUCommands::mutable_dests(int index) {
  // @@protoc_insertion_point(field_mutable:UA.AUCommands.dests)
  return dests_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >*
AUCommands::mutable_dests() {
  // @@protoc_insertion_point(field_mutable_list:UA.AUCommands.dests)
  return &dests_;
}
inline const ::UA::DetermineDst& AUCommands::dests(int index) const {
  // @@protoc_insertion_point(field_get:UA.AUCommands.dests)
  return dests_.Get(index);
}
inline ::UA::DetermineDst* AUCommands::add_dests() {
  // @@protoc_insertion_point(field_add:UA.AUCommands.dests)
  return dests_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::UA::DetermineDst >&
AUCommands::dests() const {
  // @@protoc_insertion_point(field_list:UA.AUCommands.dests)
  return dests_;
}

// repeated int64 ack = 4;
inline int AUCommands::ack_size() const {
  return ack_.size();
}
inline void AUCommands::clear_ack() {
  ack_.Clear();
}
inline ::google::protobuf::int64 AUCommands::ack(int index) const {
  // @@protoc_insertion_point(field_get:UA.AUCommands.ack)
  return ack_.Get(index);
}
inline void AUCommands::set_ack(int index, ::google::protobuf::int64 value) {
  ack_.Set(index, value);
  // @@protoc_insertion_point(field_set:UA.AUCommands.ack)
}
inline void AUCommands::add_ack(::google::protobuf::int64 value) {
  ack_.Add(value);
  // @@protoc_insertion_point(field_add:UA.AUCommands.ack)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
AUCommands::ack() const {
  // @@protoc_insertion_point(field_list:UA.AUCommands.ack)
  return ack_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
AUCommands::mutable_ack() {
  // @@protoc_insertion_point(field_mutable_list:UA.AUCommands.ack)
  return &ack_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace UA

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ups_5famazon_2eproto
